package com.zhilizhan.bhtpvz.data;


import com.hungteen.pvz.utils.StringUtil;
import com.zhilizhan.bhtpvz.BHTPvZ;
import com.zhilizhan.bhtpvz.common.block.BHTPvZBlocks;
import net.minecraft.block.Block;
import net.minecraft.data.DataGenerator;
import net.minecraftforge.client.model.generators.BlockModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * NO USE
 */
public class BHTPVZBlockModelGenerator extends BlockModelProvider{

	private Set<Block> addedBlocks = new HashSet<>();
	
	public BHTPVZBlockModelGenerator(DataGenerator generator, ExistingFileHelper existingFileHelper) {
		super(generator, BHTPvZ.MOD_ID, existingFileHelper);
	}

	@Override
	protected void registerModels() {
		//special model generated by blockbench.
		addedBlocks.addAll(Arrays.asList(BHTPvZBlocks.SCREEN_DOOR.get(), BHTPvZBlocks.WATER_POT.get(), BHTPvZBlocks.POT_GRASS.get(),
				BHTPvZBlocks.ORIGIN_MUSHROOM.get()
				));
		//crop
		genCrop(BHTPvZBlocks.CHILI.get(), 3);
		genCrop(BHTPvZBlocks.GARLIC.get(), 3);
		//up down side
		//Arrays.asList(BHTPvZBlocks.FRAGMENT_SPLICE.get(), BHTPvZBlocks.SLOT_MACHINE.get(), BHTPvZBlocks.ARMA_ORE.get(), BHTPvZBlocks.TOXIC_ORE.get()
		//		).forEach(b -> {
		//		topSideBottom(b);
		//		});
		//up side
		Arrays.asList(BHTPvZBlocks.SQUASH.get()
				).forEach(b -> {
				topSide(b);
				});
		Arrays.asList(BHTPvZBlocks.STARFRUIT_SAPLING.get()
				).forEach(b -> {
				cross(b.getRegistryName().getPath(), StringUtil.prefix("block/" + b.getRegistryName().getPath()));
				this.addedBlocks.add(b);	
				});
		Arrays.asList(BHTPvZBlocks.CHERRY_SAPLING.get()
		).forEach(b -> {
			cross(b.getRegistryName().getPath(), StringUtil.prefix("block/" + b.getRegistryName().getPath()));
			this.addedBlocks.add(b);
		});
		//last step for all normal block models.
		for(Block b : ForgeRegistries.BLOCKS) {
			if(b.getRegistryName().getNamespace().equals(BHTPvZ.MOD_ID) && ! addedBlocks.contains(b)) {
				fullCube(b);
			}
		}
	}
	
	private void fullCube(Block block) {
		cubeAll(block.getRegistryName().getPath(), StringUtil.prefix("block/" + block.getRegistryName().getPath()));
	}
	
	private void genCrop(Block block, int cnt) {
		for(int i = 0; i <= cnt; ++ i) {
			crop(block.getRegistryName().getPath() + "_" + i, StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_" + i));
		}
		this.addedBlocks.add(block);
	}
	
	private void topSideBottom(Block block) {
		cube(block.getRegistryName().getPath(), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_down"), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_top"), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_side"), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_side"), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_side"), 
			StringUtil.prefix("block/" + block.getRegistryName().getPath() + "_side")
		);
		this.addedBlocks.add(block);
	}
	
	private void topSide(Block b) {
		cubeColumn(b.getRegistryName().getPath(), StringUtil.prefix("block/" + b.getRegistryName().getPath() + "_side"), StringUtil.prefix("block/" + b.getRegistryName().getPath() + "_top"));
		this.addedBlocks.add(b);
	}
	
	@Override
	public String getName() {
		return "Plants vs Zombies block models";
	}

}
