package com.zhilizhan.bhtpvz.data;


import com.mojang.datafixers.util.Pair;
import com.zhilizhan.bhtpvz.BHTPvZ;
import com.zhilizhan.bhtpvz.common.block.BHTPvZBlocks;
import com.zhilizhan.bhtpvz.common.block.ChiliBlock;
import com.zhilizhan.bhtpvz.common.block.GarlicBlock;
import net.minecraft.block.Block;
import net.minecraft.block.CropsBlock;
import net.minecraft.data.DataGenerator;
import net.minecraft.state.Property;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.client.model.generators.ConfiguredModel;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * NO USE
 */
public class BHTPVZBlockStateGenerator extends BlockStateProvider {

	private Set<Block> addedBlocks = new HashSet<>();
	
	public BHTPVZBlockStateGenerator(DataGenerator gen, ExistingFileHelper exFileHelper) {
		super(gen, BHTPvZ.MOD_ID, exFileHelper);
	}

	@Override
	protected void registerStatesAndModels() {
		//special model generated by blockbench.
		addedBlocks.addAll(Arrays.asList(BHTPvZBlocks.SCREEN_DOOR.get(), BHTPvZBlocks.WATER_POT.get(), BHTPvZBlocks.POT_GRASS.get(),
				BHTPvZBlocks.ORIGIN_MUSHROOM.get()
				));
		//crops
		Arrays.asList(
				Pair.of(BHTPvZBlocks.CHILI.get(), ChiliBlock.AGE),
				Pair.of(BHTPvZBlocks.GARLIC.get(), GarlicBlock.AGE)
				).forEach(pair -> {
				cropBlockState(pair.getFirst(), pair.getSecond());
				});
		//last step for all normal block models.
		for(Block b : ForgeRegistries.BLOCKS) {
			if(b.getRegistryName().getNamespace().equals(BHTPvZ.MOD_ID) && ! addedBlocks.contains(b)) {
				simpleBlock(b);
			}
		}
	}
	
	private void cropBlockState(Block block, Property<Integer> p) {
		getVariantBuilder(block).forAllStates(state -> {
			int i = state.getValue(p);
			return ConfiguredModel.builder()
					.modelFile(models().crop(block.getRegistryName().getPath() + "_" + i, BHTPvZ.prefix("block/" + block.getRegistryName().getPath() + "_" + i)))
					.build();
		});
		this.addedBlocks.add(block);
	}
	
//	private void horizontalBlockState(Block block) {
//		ModelFile file = models().cubeAll(block.getRegistryName().getPath(), StringUtil.prefix("block/" + block.getRegistryName().getPath()));
//		horizontalBlock(block, file);
//	}
	
	@Override
	public String getName() {
		return "Plants vs Zombies blockstates";
	}

}
