package com.zhilizhan.bhtpvz.data;


import com.hungteen.pvz.api.types.IPlantType;

import com.hungteen.pvz.common.item.misc.PVZSpawnEggItem;
import com.hungteen.pvz.common.item.spawn.card.PlantCardItem;
import com.zhilizhan.bhtpvz.BHTPvZ;
import com.zhilizhan.bhtpvz.common.block.BHTPvZBlocks;
import com.zhilizhan.bhtpvz.common.item.BHTPvZItems;
import net.minecraft.block.Block;
import net.minecraft.data.DataGenerator;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class ItemModelGenerator extends ItemModelProvider{

	private Set<Item> addedItems = new HashSet<>();
	
	public ItemModelGenerator(DataGenerator generator, ExistingFileHelper helper) {
		super(generator, BHTPvZ.MOD_ID, helper);
	}

	@Override
	protected void registerModels() {
		//special model generated by blockbench.
		//addedItems.addAll(Arrays.asList(BHTPvZItems.PEA_GUN.get(), BHTPvZItems.ZOMBIE_FLAG.get(), BHTPvZItems.BOBSLE_CAR.get(),
		//		BHTPvZItems.SCREEN_DOOR.get(), BHTPvZItems.JACK_BOX.get(), BHTPvZItems.BALLOON.get(),
		//		BHTPvZItems.WARNING_SIGN.get(), BHTPvZItems.ZOMBIE_DOLL.get(), BHTPvZItems.POLE.get(),
		//		BHTPvZItems.BUCKET_HEAD.get(), BHTPvZItems.RESOURCE_COLLECTOR.get()
		//		));
		//single add
		Arrays.asList(BHTPvZItems.GOO_PEA.get(), BHTPvZItems.ORIGIN_SPORE.get(), BHTPvZItems.CHILI_SEEDS.get(), BHTPvZItems.STARFRUIT.get()
				
				).forEach(i -> {
			genNormalModel(i);
			this.addedItems.add(i);
		});
		Arrays.asList(BHTPvZBlocks.STARFRUIT_SAPLING.get(),BHTPvZBlocks.CHERRY_SAPLING.get(), BHTPvZBlocks.SCREEN_DOOR.get()).forEach(i -> {
			genItemModelWithBlock(i.asItem());
			this.addedItems.add(i.asItem());
		});
		//for mostly common items.
		for (Item i : ForgeRegistries.ITEMS) {
			if(! i.getRegistryName().getNamespace().equals(BHTPvZ.MOD_ID) || addedItems.contains(i)) continue ;
			if (i instanceof PVZSpawnEggItem) {//for spawn eggs
				addedItems.add(i);
				getBuilder(i.getRegistryName().getPath()).parent(getExistingFile(new ResourceLocation("item/template_spawn_egg")));
			} else if(i instanceof PlantCardItem) {//for plant cards
				IPlantType plant = ((PlantCardItem) i).plantType;
				ResourceLocation plantResource = new ResourceLocation(plant.getModID(), "screenshot/plant/" + plant.toString());
				addedItems.add(i);
				if(((PlantCardItem) i).isEnjoyCard) {
					ResourceLocation r = BHTPvZ.prefix("item/misc/mega_card");
					genNormal(i.getRegistryName().getPath(), r, plantResource);
				} else {
					genNormal(i.getRegistryName().getPath(), BHTPvZ.prefix("item/misc/" + plant.getRank().getName() + "_card"), plantResource);
				}
			} else if(i instanceof BlockItem) {
				addedItems.add(i);
				genBlockModel(((BlockItem) i).getBlock());
			}
		}
		//for hand held item
		Arrays.asList(BHTPvZItems.DAMSON_CRYSTAL_AXE.get(), BHTPvZItems.DAMSON_CRYSTAL_HOE.get(), BHTPvZItems.DAMSON_CRYSTAL_PICKAXE.get(), BHTPvZItems.DAMSON_CRYSTAL_SHOVEL.get(),
				BHTPvZItems.DAMSON_CRYSTAL_SWORD.get()
				).forEach(i -> {
			addedItems.add(i);
			genHeld(i.getRegistryName().getPath(), BHTPvZ.prefix("item/" + i.getRegistryName().getPath()));
		});
		//2 types of xp storage sapling.
		genSameModelsWithAdd(BHTPvZItems.WISDOM_SAPLING.get(), BHTPvZItems.XP_SAPLING.get());
		//last step for all normal item models.
		for(Item i : ForgeRegistries.ITEMS) {
			if(i.getRegistryName().getNamespace().equals(BHTPvZ.MOD_ID) && ! addedItems.contains(i)) {
				genNormal(i.getRegistryName().getPath(), BHTPvZ.prefix("item/" + i.getRegistryName().getPath()));
			}
		}
	}
	
	/**
	 * for items with the same texture.
	 */
	private void genSameModelsWithAdd(Item... items) {
		final Item first = items[0];
		for(Item i : items) {
			genNormal(i.getRegistryName().getPath(), BHTPvZ.prefix("item/" + first.getRegistryName().getPath()));
		    this.addedItems.add(i);
		}
	}
	
	private void genNormalModel(Item i) {
		genNormal(i.getRegistryName().getPath(), BHTPvZ.prefix("item/" + i.getRegistryName().getPath()));
	}
	
	private ItemModelBuilder genNormal(String name, ResourceLocation... layers) {
		return gen(name, "item/generated", layers);
	}
	
	private ItemModelBuilder genHeld(String name, ResourceLocation... layers) {
		return gen(name, "item/handheld", layers);
	}
	
	private ItemModelBuilder gen(String name, String parent, ResourceLocation... layers) {
		ItemModelBuilder builder = withExistingParent(name, parent);
		for (int i = 0; i < layers.length; i++) {
			builder = builder.texture("layer" + i, layers[i]);
		}
		return builder;
	}
	
	private void genBlockModel(Block b) {
		withExistingParent(b.getRegistryName().getPath(), BHTPvZ.prefix("block/" + b.getRegistryName().getPath()));
	}
	
	private void genItemModelWithBlock(Item i) {
		genNormal(i.getRegistryName().getPath(), BHTPvZ.prefix("block/" + i.getRegistryName().getPath()));
	}
	
	@Override
	public String getName() {
		return "Plants vs Zombies item and itemblock models";
	}

}
